### PR TITLE
Move to TypeScript

### PR DESCRIPTION
**Pull request by dmythro**
Move everything to TypeScript. Type-safe, awesome auto-complete for IDE.

image

image

image

image

- [x] Add TypeScript to project
- [x] Move main to TypeScript (index.ts)
- [x] Configure Rollup
- [x] Remove full data file
- [x] Move scripts to TypeScript
  - [x] Minify JSON
  - [x] Generate CSV
  - [x] Generate SQL
  - [x] Generate ES5 export with `.d.ts`
  - [x] Update ES5 export tests
  - [x] Generate emoji for countries
  - [x] Generate minimal files
- [x] Fix main test
- [x] Remove Gulp

### Rework

- [ ] Rework languages lists (in use, not in use)
- [x] Rework currency codes (comma-separated string to array of codes)
- [x] Rework phone codes (comma-separated string to array of codes)
- [x] Rework continent codes (support [transcontinental countries](url))
- [x] Introduce extra modules
  - [x] Country Emoji module
  - [x] 2to3, 3to2 module

### CODE REVIEW

**Comment by seanonthenet** [comment]
This is super needed! Is it still WIP?

**Comment by dmythro** [comment]
> This is super needed! Is it still WIP?

I'm going to finish / release it next days. Finally a vacation!

**Comment by seanonthenet** [comment]
Awesome :) +1

**Comment by dmythro** [comment]
Merging this to master, but some rework is still probably required to release v3. Will review this once again and make separate PRs instead of pushing to the same already huge one.

**Pull request merged**
